INSERT INTO tb_categoria (nome, registro_criado) VALUES ('Livros', CURRENT_TIMESTAMP);
INSERT INTO tb_categoria (nome, registro_criado) VALUES ('Eletronicos', CURRENT_TIMESTAMP);
INSERT INTO tb_categoria (nome, registro_criado) VALUES ('Computadores', CURRENT_TIMESTAMP);

INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Kindle Paperwhite', 'Leitor de e-books com tela 6\" e iluminação embutida', 11.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Fone sem fio AirPods Pro', 'Fone intra-auricular com cancelamento de ruído e estojo de carregamento', 12.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Smartphone Galaxy S21', 'Smartphone com tela AMOLED, múltiplas câmeras e 128GB de armazenamento', 13.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Smart TV 55\" 4K', 'TV LED 55 polegadas com resolução 4K e HDR', 14.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Notebook Dell Inspiron 15', 'Notebook 15\" com processador Intel e 8GB de RAM', 15.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Monitor 27\" IPS', 'Monitor 27 polegadas IPS com resolução Full HD e entrada HDMI', 16.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Teclado mecânico RGB', 'Teclado mecânico com switches táteis e iluminação RGB', 17.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Mouse óptico wireless', 'Mouse sem fio ergonômico com sensor óptico de alta precisão', 18.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('SSD NVMe 1TB', 'Unidade de estado sólido NVMe de 1TB para alto desempenho', 19.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('HD Externo 2TB', 'Disco rígido externo 2TB USB 3.0 para backup e armazenamento', 20.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Roteador Wi-Fi 6', 'Roteador com padrão Wi-Fi 6 para redes domésticas de alta velocidade', 21.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Caixa de som Bluetooth', 'Caixa portátil Bluetooth com som estéreo e bateria de longa duração', 22.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Smartwatch Fitness', 'Relógio inteligente com monitor de batimentos, GPS e notificações', 23.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Câmera Mirrorless 24MP', 'Câmera mirrorless compacta com sensor 24MP e gravação em 4K', 24.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Lente 50mm f/1.8', 'Lente prime 50mm ideal para retratos com grande abertura', 25.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Microfone USB Condensador', 'Microfone condensador USB para gravação de voz e streaming', 26.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Webcam Full HD', 'Webcam 1080p para videoconferência com microfone embutido', 27.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Impressora Multifuncional', 'Impressora jato de tinta com scanner e função duplex', 28.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Scanner Portátil', 'Scanner portátil para digitalização rápida de documentos', 29.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Cadeira Gamer', 'Cadeira ergonômica com ajuste de altura e apoio lombar', 30.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Mesa para escritório', 'Mesa compacta com tampo em madeira e suporte para monitor', 31.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Mochila para laptop 15\"', 'Mochila resistente com compartimento para laptop 15 polegadas', 32.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Carregador portátil 20000mAh', 'Power bank com duas saídas USB e carregamento rápido', 33.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Cabo USB-C 1m', 'Cabo USB-C para transferência de dados e carregamento rápido', 34.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Hub USB 4 portas', 'Hub USB alimentado com 4 portas para expansão de conexões', 35.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Placa de vídeo GTX 1660', 'Placa de vídeo para jogos com bom desempenho em 1080p', 36.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Fonte 650W 80+ Bronze', 'Fonte de alimentação com certificação 80+ Bronze e proteção contra surtos', 37.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Memória RAM 16GB DDR4', 'Pente de memória 16GB DDR4 com alta frequência para multitarefa', 38.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Processador Intel i5 10400', 'Processador Intel de 6 núcleos para uso geral e jogos leves', 39.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Processador AMD Ryzen 5 3600', 'CPU AMD 6 núcleos com bom custo-benefício para produtividade', 40.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Placa-mãe ATX', 'Placa-mãe ATX com suporte a múltiplas conexões e expansão', 41.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Refrigeração líquida 240mm', 'Sistema de refrigeração líquida para redução de temperatura da CPU', 42.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Estabilizador de voltagem', 'Estabilizador para proteção de equipamentos eletrônicos contra variações', 43.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Filtro de linha 6 tomadas', 'Filtro de linha com proteção contra surtos e 6 tomadas', 44.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Lâmpada LED 10W', 'Lâmpada LED econômica com brilho equivalente a 60W', 45.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Aquecedor portátil', 'Aquecedor elétrico portátil com ajuste de temperatura', 46.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Ventilador 40cm', 'Ventilador de mesa 40cm com múltiplas velocidades', 47.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Relógio de parede analógico', 'Relógio de parede com design minimalista e mecanismo silencioso', 48.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Conjunto teclado e mouse', 'Kit teclado membrana e mouse óptico para escritório', 49.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Câmera de segurança 1080p', 'Câmera IP com resolução 1080p e visão noturna', 50.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Kit de lâminas de barbear', 'Conjunto com 5 lâminas de reposição para barbeador', 51.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Secador de cabelo 2000W', 'Secador com potência de 2000W e múltiplas temperaturas', 52.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Aspirador vertical', 'Aspirador vertical sem fio com bateria de longa duração', 53.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Panela elétrica', 'Panela elétrica multifunção para arroz, cozimento e aquecimento', 54.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Liquidificador 700W', 'Liquidificador potente de 700W com copo de vidro', 55.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Conjunto de panelas 5 peças', 'Conjunto antiaderente com 5 peças e tampas de vidro', 56.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Escova elétrica de dentes', 'Escova elétrica com múltiplos modos de limpeza e temporizador', 57.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Purificador de água', 'Purificador de água com sistema de filtragem por carvão e membrana', 58.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Cafeteira espresso', 'Cafeteira espresso compacta com 15 bars de pressão', 59.00, CURRENT_TIMESTAMP);
INSERT INTO tb_produto (nome, descricao, preco, data) VALUES ('Livro: Clean Code', 'Livro sobre boas práticas de desenvolvimento de software e código limpo', 60.00, CURRENT_TIMESTAMP);

INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (1, 1);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (2, 2);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (2, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (3, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (4, 1);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (4, 2);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (5, 2);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (6, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (6, 1);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (7, 1);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (8, 2);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (8, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (9, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (10, 1);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (10, 2);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (11, 2);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (12, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (12, 1);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (13, 1);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (14, 2);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (14, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (15, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (16, 1);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (16, 2);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (17, 2);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (18, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (18, 1);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (19, 1);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (20, 2);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (20, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (21, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (22, 1);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (22, 2);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (23, 2);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (24, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (24, 1);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (25, 1);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (26, 2);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (26, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (27, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (28, 1);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (28, 2);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (29, 2);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (30, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (30, 1);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (31, 1);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (32, 2);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (32, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (33, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (34, 1);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (34, 2);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (35, 2);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (36, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (36, 1);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (37, 1);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (38, 2);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (38, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (39, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (40, 1);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (40, 2);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (41, 2);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (42, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (42, 1);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (43, 1);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (44, 2);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (44, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (45, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (46, 1);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (46, 2);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (47, 2);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (48, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (48, 1);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (49, 1);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (50, 2);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (50, 3);
