CREATE TABLE tb_user_role (
user_id BIGINT NOT NULL,
role_id BIGINT NOT NULL,
PRIMARY KEY (user_id, role_id),
CONSTRAINT fk_user
FOREIGN KEY (user_id)
REFERENCES tb_user (id)
ON UPDATE NO ACTION
ON DELETE NO ACTION,
CONSTRAINT fk_role
FOREIGN KEY (role_id)
REFERENCES tb_role (id)
ON UPDATE NO ACTION
ON DELETE NO ACTION
);
